server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://vUbuntu4:8001/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: routes_A
          uri: lb://service-A
          predicates:
            - Path=/pre/A/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/defaultfallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 4000 # 请求整体耗时大于该时间，就服务熔断

