#是否开启pasm登录验证
pasm.login.enable=true
#是否开启多IP
pasm.multi.ip=false
#应用系统简称，例如：PASM
iam.security.resource.appname=SpringCloud0
#内网ucas地址配置
iam.server.url=http://vubuntu5:58045/ucas
#内网应用地址配置
local.service.url=http://127.0.0.1:8101/prefix/A/m1
#该配置为登出拦截url类型配置
iam.cas.signOutFilters=/prefix/*
#该配置为cas用户认证拦截url类型
iam.cas.authFilters=/prefix/*
#该配置为校验票据拦截url类型
iam.cas.validateFilters=/*
#该配置为可以从session中获取当前登录账号的url类型
iam.cas.requestWrapperFilters=/*
#该配置为可以从线程中获取当前登录账号的url类型
iam.cas.assertionFilters=/*
#该配置为cas的配置默认true
iam.cas.redirectAfterValidation=true
#该配置为cas的配置默认true
iam.cas.useSession=true
#pasm的rmi接口的ip
iam.rmi.server.ip=vubuntu5
#pasm的rmi接口的端口
iam.rmiPort=52099