server.port=8101
spring.cloud.nacos.discovery.server-addr=vUbuntu4:8848

# 开启从注册中心动态创建路由功能，利用微服务名进行路由
spring.cloud.gateway.discovery.locator.enabled=true

# gateway 路由配置，第一种方式
spring.cloud.gateway.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=routes_A
spring.cloud.gateway.routes[0].uri=lb://serviceA
spring.cloud.gateway.routes[0].predicates[0]=Path=/prefix/A/**
# 以 / 分隔，去掉第几部分后转发 如 http://ip:8101/prefix/A/m1--->http://vubuntu4:8901/A/m1
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
# spring.cloud.gateway.routes[0].filters[1]=RewritePath=/httpbin/(?<segment>.*), /$\{segment}

# 连接 sentinel
spring.cloud.sentinel.transport.dashboard=vUbuntu4:8080
spring.cloud.sentinel.transport.port=8719
 Sentinel 网关流控默认的粒度是 route 维度以及自定义 API 分组维度，默认不支持 URL 粒度 若在网关流控控制台上看到了 URL 资源，就是此配置项没有置为 false
spring.cloud.sentinel.filter.enabled=false

