server.port=8902
spring.cloud.nacos.discovery.server-addr=vUbuntu4:8848
spring.cloud.sentinel.transport.dashboard=vUbuntu4:8080
spring.cloud.sentinel.transport.port=8719

management.endpoints.web.exposure.include='*'

# 是否 启用feign sentinel 服务降级
feign.sentinel.enabled=true

sleep.s=0
value=test2