server.port=8901
spring.cloud.nacos.discovery.server-addr=vUbuntu4:8848

management.endpoints.web.exposure.include='*'

# 连接 sentinel
spring.cloud.sentinel.transport.dashboard=vUbuntu4:8080
spring.cloud.sentinel.transport.port=8719
# 是否 启用feign sentinel 服务降级
feign.sentinel.enabled=true
# 连接超过多少ms降级
feign.client.config.default.connectTimeout=3000
# 读取超过多少ms降级
feign.client.config.default.readTimeout=3000

sleep.s=0